project:
  type: book

book:
  title: "MBAT Club Datathon 2026 — Participant Manual"
  author: "MBAT Club"
  chapters:
    - index.qmd
    - code-of-conduct.qmd
    - git-github.qmd
    - quarto-guide.qmd
    - starter-template.qmd
    - part: "Databases + MongoDB"
      chapters:
        - sqlnosql.qmd
        - mongodbcon.qmd
    - data-dict.qmd
    - tidytext.qmd
    - visualisation-tables.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



