project:
  type: book

book:
  title: "Datathon Instruction Manual"
  author: "MBAT Hang"
  chapters:
    - index.qmd
    - mongodbcon.qmd
    - sqlnosql.qmd 
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



